"""empty message

Revision ID: 1755f99ac5a4
Revises: 
Create Date: 2026-01-02 03:46:33.361007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1755f99ac5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('uq_follower_pair', ['follower_id', 'followed_id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_follower_pair', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
