"""empty message

Revision ID: 7fc387f1d9de
Revises: 78f2b0f7a0f6
Create Date: 2026-01-12 02:40:34.997332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc387f1d9de'
down_revision = '78f2b0f7a0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_home', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=200), nullable=False))
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('public_id')

    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('publish_home')

    # ### end Alembic commands ###
