"""empty message

Revision ID: d729f9592f16
Revises: f4f8c9e09a47
Create Date: 2026-01-12 04:58:03.293428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd729f9592f16'
down_revision = 'f4f8c9e09a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('publish_home', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_posts', schema=None) as batch_op:
        batch_op.drop_column('publish_home')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
